apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wazuh-operator.fullname" . }}
  labels:
    {{- include "wazuh-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "wazuh-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "wazuh-operator.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "wazuh-operator.serviceAccountName" . }}
      containers:
      - name: operator
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
        - /usr/local/bin/wazuh-operator
        - run
        - --namespace
        - all
        env:
        - name: RUST_LOG
          value: {{ .Values.logLevel | quote }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
