apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "wazuh-operator.serviceAccountName" . }}
  labels:
    {{- include "wazuh-operator.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "wazuh-operator.fullname" . }}-role
  labels:
    {{- include "wazuh-operator.labels" . | nindent 4 }}
rules:
- apiGroups: ["wazuh.adorsys.team"]
  resources: ["wazuhindexerclusters", "wazuhmanagerclusters", "wazuhdashboards", "wazuhagentgroups", "wazuhconfigs", "wazuhdecoders", "wazuhindexerindextemplates", "wazuhindexersecurities", "wazuhindexerusers", "wazuhlisteners", "wazuhrules"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["wazuh.adorsys.team"]
  resources: ["wazuhindexerclusters/status", "wazuhmanagerclusters/status", "wazuhdashboards/status", "wazuhagentgroups/status", "wazuhconfigs/status", "wazuhdecoders/status", "wazuhindexerindextemplates/status", "wazuhindexersecurities/status", "wazuhindexerusers/status", "wazuhlisteners/status", "wazuhrules/status"]
  verbs: ["get", "update", "patch"]
- apiGroups: ["apps"]
  resources: ["statefulsets", "deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["services", "endpoints", "pods", "configmaps", "secrets", "persistentvolumeclaims", "serviceaccounts"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "wazuh-operator.fullname" . }}-binding
  labels:
    {{- include "wazuh-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "wazuh-operator.fullname" . }}-role
subjects:
- kind: ServiceAccount
  name: {{ include "wazuh-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
