apiVersion: wazuh.adorsys.team/v1alpha1
kind: WazuhIndexerCluster
metadata:
  name: wazuh-indexer-secured
  namespace: wazuh-test
spec:
  replicas: 3
  version: "4.14.0"
  storage:
    size: "1Gi"
  tls:
    enabled: true
    cert_secret: indexer-tls-certs
---
apiVersion: v1
kind: Secret
metadata:
  name: wazuh-manager-api-auth
  namespace: wazuh-test
stringData:
  username: wazuh-api
  password: wazuh-api-password
---
apiVersion: wazuh.adorsys.team/v1alpha1
kind: WazuhManagerCluster
metadata:
  name: wazuh-manager-secured
  namespace: wazuh-test
spec:
  replicas: 0
  version: "4.14.0"
  apiSecretRef:
    name: wazuh-manager-api-auth
  indexer_cluster:
    name: wazuh-indexer-secured
  tls:
    enabled: true
---
apiVersion: wazuh.adorsys.team/v1alpha1
kind: WazuhManager
metadata:
  name: wazuh-manager-secured-master
  namespace: wazuh-test
spec:
  cluster_ref:
    name: wazuh-manager-secured
  replicas: 2
  role: master
---
apiVersion: wazuh.adorsys.team/v1alpha1
kind: WazuhManager
metadata:
  name: wazuh-manager-secured-worker
  namespace: wazuh-test
spec:
  cluster_ref:
    name: wazuh-manager-secured
  replicas: 2
  role: worker
