apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: wazuhclusters.wazuh.adorsys.team
spec:
  group: wazuh.adorsys.team
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                replicas:
                  type: integer
                  minimum: 1
            status:
              type: object
              properties:
                available_replicas:
                  type: integer
      additionalPrinterColumns:
        - name: Replicas
          type: integer
          description: "Number of desired replicas"
          jsonPath: .spec.replicas
        - name: Available Replicas
          type: integer
          description: "Number of available replicas"
          jsonPath: .status.available_replicas
  scope: Namespaced
  names:
    plural: wazuhclusters
    singular: wazuhcluster
    kind: WazuhCluster
    shortNames:
      - wzcl
