apiVersion: wazuh.adorsys.team/v1alpha1
kind: WazuhListener
metadata:
  name: custom-syslog-listener
  namespace: wazuh-system
spec:
  clusterName: wazuh-manager
  port: 514
  protocol: udp
  type: syslog
