image:
  repository: wazuh-operator
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

serviceAccount:
  create: true
  name: ""

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

logLevel: info
