apiVersion: v1
kind: ServiceAccount
metadata:
  name: wazuh-operator
  namespace: wazuh-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wazuh-operator-role
rules:
- apiGroups: ["wazuh.com"]
  resources: ["wazuhindexerclusters", "wazuhmanagerclusters", "wazuhdashboards"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["wazuh.com"]
  resources: ["wazuhindexerclusters/status", "wazuhmanagerclusters/status", "wazuhdashboards/status"]
  verbs: ["get", "update", "patch"]
- apiGroups: ["apps"]
  resources: ["statefulsets", "deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["services", "endpoints", "pods", "configmaps", "secrets", "persistentvolumeclaims", "serviceaccounts"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wazuh-operator-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: wazuh-operator-role
subjects:
- kind: ServiceAccount
  name: wazuh-operator
  namespace: wazuh-system
