apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wazuh-operator-services-role
rules:
- apiGroups: [""]
  resources: ["services", "endpoints", "serviceaccounts"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wazuh-operator-services-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: wazuh-operator-services-role
subjects:
- kind: ServiceAccount
  name: wazuh-operator
  namespace: wazuh-system
